USE [master]
GO

/****** Object:  Database [Boards]    Script Date: 11.01.2021 12:40:10 ******/
CREATE DATABASE [Boards]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Boards', FILENAME = N'G:\Sql\Boards.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Boards_log', FILENAME = N'G:\Sql\Logs\Boards_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Boards].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Boards] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Boards] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Boards] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Boards] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Boards] SET ARITHABORT OFF 
GO

ALTER DATABASE [Boards] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Boards] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Boards] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Boards] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Boards] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Boards] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Boards] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Boards] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Boards] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Boards] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Boards] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Boards] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Boards] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Boards] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Boards] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Boards] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Boards] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Boards] SET RECOVERY FULL 
GO

ALTER DATABASE [Boards] SET  MULTI_USER 
GO

ALTER DATABASE [Boards] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Boards] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Boards] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Boards] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Boards] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Boards] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Boards] SET  READ_WRITE 
GO


