version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-rabbitmq}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-rabbitmq}
    ports:
        - 5672:5672
        - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
  board.web:
    image: ${DOCKER_REGISTRY-}boardweb
    container_name: Board.Web
    restart: on-failure
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: Board.Web\Dockerfile
  boards.Items:
    image: ${DOCKER_REGISTRY-}boardsitems
    container_name: Boards.Items
    restart: on-failure
    depends_on:
      - rabbitmq
    ports:
      - "8081:80"
    build:
      context: .
      dockerfile: BoardItemGetAllQueryService\Dockerfile
