version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
  board.web:
    image: ${DOCKER_REGISTRY-}boardweb
    container_name: Board.Web
    build:
      context: .
      dockerfile: Board.Web\Dockerfile
