version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-rabbitmq}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-rabbitmq}
    ports:
        - 5672:5672
        - 15672:15672
    restart: on-failure
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 1s
      timeout: 10s
      retries: 100

  boards.front:
    image: ${DOCKER_REGISTRY-}boardsfront
    depends_on:
      - rabbitmq
      - boards.users
      - boards.boards
      - boards.posts
      - boards.files
    build:
      context: .
      dockerfile: Boards.Front.API\Dockerfile
    restart: on-failure
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "80" ]
      interval: 1s
      timeout: 10s
      retries: 100

  boards.posts:
    image: ${DOCKER_REGISTRY-}boardsposts
    build:
      context: .
      dockerfile: Boards.Posts.API/Dockerfile
    restart: on-failure
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "80" ]
      interval: 1s
      timeout: 10s
      retries: 100

  boards.files:
    image: ${DOCKER_REGISTRY-}boardsfiles
    build:
      context: .
      dockerfile: Boards.Files.API/Dockerfile
    restart: on-failure
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "80" ]
      interval: 1s
      timeout: 10s
      retries: 100

  boards.boards:
    image: ${DOCKER_REGISTRY-}boardsboards
    build:
      context: .
      dockerfile: Boards.Boards.API/Dockerfile
    restart: on-failure
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "80" ]
      interval: 1s
      timeout: 10s
      retries: 100

  boards.users:
    image: ${DOCKER_REGISTRY-}boardsusers
    build:
      context: .
      dockerfile: Boards.Users.API/Dockerfile
    restart: on-failure
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "80" ]
      interval: 1s
      timeout: 10s
      retries: 100

