version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-rabbitmq}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-rabbitmq}
    ports:
        - 5672:5672
        - 15672:15672
    #healthcheck:
    #  test: [ "CMD", "nc", "-z", "localhost", "5672" ]
    #  interval: 5s
    #  timeout: 15s
    #  retries: 1
  boards.front:
    image: ${DOCKER_REGISTRY-}boardsfront
    #restart: on-failure
    depends_on:
      - rabbitmq
      - boards.posts
    build:
      context: .
      dockerfile: Boards.Front.API\Dockerfile
  boards.posts:
    image: ${DOCKER_REGISTRY-}boardsposts
    build:
      context: .
      dockerfile: Boards.Posts.API/Dockerfile
  boards.files:
    image: ${DOCKER_REGISTRY-}boardsfiles
    build:
      context: .
      dockerfile: Boards.Files.API/Dockerfile
  boards.boards:
    image: ${DOCKER_REGISTRY-}boardsboards
    build:
      context: .
      dockerfile: Boards.Boards.API/Dockerfile
  boards.users:
    image: ${DOCKER_REGISTRY-}boardsusers
    build:
      context: .
      dockerfile: Boards.Users.API/Dockerfile

